services: 
  bwapp:
    build: 
      context: .
    ports: 
      - "80:80"
  jenkins:
    build: 
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - .:/app
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    user: jenkins